export enum Role {
  CUSTOMER            = 'CUSTOMER',
  CONSULTANTS         = 'CONSULTANTS',
  BUILDERS_CONTRACTORS = 'BUILDERS_CONTRACTORS',
  VENDORS             = 'VENDORS',
  OTHERS              = 'OTHERS',
}
 
// Sub Category 1 enums
export enum ConsultantSubCat1 {
  DESIGNERS  = 'DESIGNERS',
  ENGINEERS  = 'ENGINEERS',
  PMC        = 'PMC',
  MARKETING  = 'MARKETING',
  OTHERS     = 'OTHERS',
}
 
export enum BuilderSubCat1 {
  CORE_CONTRACTORS                 = 'CORE_CONTRACTORS',
  CIVIL_STRUCTURAL_CONTRACTORS     = 'CIVIL_STRUCTURAL_CONTRACTORS',
  BUILDING_ENVELOPE_CONTRACTORS    = 'BUILDING_ENVELOPE_CONTRACTORS',
  MEP_CONTRACTORS                  = 'MEP_CONTRACTORS',
  VERTICAL_TRANSPORTATION          = 'VERTICAL_TRANSPORTATION',
  INTERIOR_FINISHING_CONTRACTORS   = 'INTERIOR_FINISHING_CONTRACTORS',
  EXTERNAL_WORKS_CONTRACTORS       = 'EXTERNAL_WORKS_CONTRACTORS',
  SPECIALIZED_CONTRACTORS          = 'SPECIALIZED_CONTRACTORS',
  OPERATIONS_MAINTENANCE           = 'OPERATIONS_MAINTENANCE',
}
 
export enum VendorSubCat1 {
  STRUCTURAL_CIVIL_VENDORS         = 'STRUCTURAL_CIVIL_VENDORS',
  ARCHITECTURAL_VENDORS            = 'ARCHITECTURAL_VENDORS',
  MEP_VENDORS                      = 'MEP_VENDORS',
  FIRE_SAFETY_VENDORS              = 'FIRE_SAFETY_VENDORS',
  ELV_ICT_VENDORS                  = 'ELV_ICT_VENDORS',
  VERTICAL_TRANSPORTATION_VENDORS  = 'VERTICAL_TRANSPORTATION_VENDORS',
  EXTERNAL_WORKS_VENDORS           = 'EXTERNAL_WORKS_VENDORS',
  SPECIALIZED_VENDORS              = 'SPECIALIZED_VENDORS',
  CONSTRUCTION_EQUIPMENT_VENDORS   = 'CONSTRUCTION_EQUIPMENT_VENDORS',
}
 
// Sub Category 3 — project types (same for ALL sub cat 2 selections)
export enum ProjectType {
  RESIDENTIAL     = 'RESIDENTIAL',
  COMMERCIAL      = 'COMMERCIAL',
  HEALTHCARE      = 'HEALTHCARE',
  HOSPITALITY     = 'HOSPITALITY',
  EDUCATIONAL     = 'EDUCATIONAL',
  INDUSTRIAL      = 'INDUSTRIAL',
  INFRASTRUCTURE  = 'INFRASTRUCTURE',
  INSTITUTIONAL   = 'INSTITUTIONAL',
  CULTURAL        = 'CULTURAL',
  WAREHOUSING     = 'WAREHOUSING',
  MIXED_USE       = 'MIXED_USE',
  TRANSPORTATION  = 'TRANSPORTATION',
  GOVERNMENT      = 'GOVERNMENT',
  RECREATIONAL    = 'RECREATIONAL',
  IT_CENTRES      = 'IT_CENTRES',
}